# Generated by Django 5.2.1 on 2025-06-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите своё аватар",
                null=True,
                upload_to="users/avatars/",
                verbose_name="Аватар",
            ),
        ),
    ]
