# Generated by Django 5.2.1 on 2025-05-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="Заголовок", max_length=150, verbose_name="Заголовок")),
                (
                    "content",
                    models.TextField(blank=True, help_text="Содержимое", null=True, verbose_name="Содержимое"),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="blog/images", verbose_name="Изображение"),
                ),
                ("created_at", models.DateField(auto_now_add=True, verbose_name="Дата создания")),
                ("sign", models.BooleanField(verbose_name="Признак публикации")),
                ("views_cnt", models.IntegerField(default="0", verbose_name="Количество просмотров")),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
                "ordering": ["title", "created_at", "views_cnt"],
            },
        ),
    ]
