# Generated by Django 5.2.1 on 2025-05-17 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Внесите название категории", max_length=150, verbose_name="Наименование"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Внесите описание категории", null=True, verbose_name="Описание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Внесите название продукта", max_length=150, verbose_name="Наименование"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Внесите описание продукта", null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="data/media/product_images", verbose_name="Изображение"
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Цена за покупку")),
                ("created_at", models.DateField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateField(auto_now=True, verbose_name="Дата последнего изменения")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Внесите название категории продукта",
                        max_length=150,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ["name", "created_at"],
            },
        ),
    ]
