# Generated by Django 5.2.1 on 2025-05-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Имя")),
                ("phone", models.CharField(max_length=30, verbose_name="Телефон")),
                ("message", models.TextField(max_length=300, verbose_name="Сообщение")),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product/images", verbose_name="Изображение"),
        ),
    ]
