# Generated by Django 5.2.1 on 2025-06-14 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_options_product_is_published_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "created_at"],
                "permissions": [
                    ("can_add_product", "Добавление продуктов"),
                    ("can_change_product", "Изменение продуктов"),
                    ("can_unpublish_product", "Отмена публикации продуктов"),
                    ("can_view_unpublished", "Просмотр неопубликованных товаров"),
                    ("can_delete_product", "Удаление продуктов"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
